In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from shapely.geometry import Point
from shapely.ops import transform
import pyproj
from functools import partial
from collections import Counter
import pickle
from rtree import index

In [2]:
def gera_isocota(ponto, raio):
    raio_ponto_de_estudo_utm = lat_lng_to_utm(ponto).buffer(raio)
    raio_ponto_de_estudo_lat_lng = utm_to_lat_lng(raio_ponto_de_estudo_utm)
    return raio_ponto_de_estudo_lat_lng


def lat_lng_to_utm(lat_lng_geom):
    project = partial(
        pyproj.transform,
        pyproj.Proj(init='epsg:4326'),  # source coordinate system
        pyproj.Proj(init='epsg:3857'))  # destination coordinate system
    utm_geom = transform(project, lat_lng_geom)
    return utm_geom


def utm_to_lat_lng(utm_geom):
    project = partial(
        pyproj.transform,
        pyproj.Proj(init='epsg:3857'),  # source coordinate system
        pyproj.Proj(init='epsg:4326'))  # destination coordinate system
    lat_lng_geom = transform(project, utm_geom)
    return lat_lng_geom


def obtem_configuracao():
    return {'faculdades', 'escolas', 'ponto_de_onibus', 'concorrentes__grandes_redes',
            'concorrentes__pequeno_varejista', 'minhas_lojas', 'agencia_bancaria', 'padaria',
            'acougue', 'restaurante', 'correio', 'loterica'}

In [3]:
df_pois = pd.read_csv('pois.csv')
df_pois

          id   latitude  longitude    tipo_POI
0          0 -22.818201 -46.988467  faculdades
1          1 -23.009421 -47.179460  faculdades
2          2 -22.861652 -46.941259  faculdades
3          3 -23.000854 -47.167633  faculdades
4          4 -22.917815 -47.121111  faculdades
...      ...        ...        ...         ...
31214  31214 -22.954946 -47.048017    loterica
31215  31215 -22.901880 -46.904071    loterica
31216  31216 -22.902293 -47.100895    loterica
31217  31217 -22.922585 -47.185374    loterica
31218  31218 -22.922331 -47.201397    loterica

[31219 rows x 4 columns]

In [5]:
area_de_influencia = 1000
target_pois = {}
data = pd.DataFrame([{'latitude': -22.818201,
        'longitude': -46.988467}])

for row in data.itertuples():
    lat, lng = row.latitude, row.longitude
    pt = Point(lng, lat)
    isocota = gera_isocota(pt, area_de_influencia)
    min_lng, min_lat, max_lng, max_lat = isocota.bounds
    mask = (df_pois.latitude.between(min_lat, max_lat) &
                    df_pois.longitude.between(min_lng, max_lng))
    counter = Counter()
    for row_poi in df_pois.loc[mask].itertuples():
        if Point(row_poi.longitude, row_poi.latitude).within(isocota):
            counter.update([row_poi.tipo_POI])
    target_pois[row.Index] = counter

df_data = pd.DataFrame.from_dict(target_pois, orient='Index').fillna(0)
for i in obtem_configuracao():
    if i not in df_data:
        df_data[i] = 0
        
df_data

/home/hnp/anaconda3/lib/python3.9/site-packages/pyproj/crs/crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
/home/hnp/anaconda3/lib/python3.9/site-packages/pyproj/crs/crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
/home/hnp/anaconda3/lib/python3.9/site-packages/pyproj/crs/crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
/home/hnp/anaconda3/lib/python3.9/site-packages/pyproj/crs/crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

,faculdades,escolas,ponto_de_onibus,concorrentes__pequeno_varejista,agencia_bancaria,padaria,acougue,restaurante,correio,loterica,concorrentes__grandes_redes,minhas_lojas
0,2,5,13,1,20,35,10,3,1,2,0,0

In [14]:
df_data.iloc[0].concorrentes__pequeno_varejista
df_data.iloc[0].concorrentes__grandes_redes

0